### ISSUE TITLE
1964 Showing Dan Bryan's Name

### ISSUE THREAD

**Issue by TomatDividedBy0** [newcampaigntrail/newcampaigntrail#41]
I've been looking into fixing it, and while I haven't come up with a complete answer yet, here's what I know:

- The credits attribute is currently its own separate JSON which gets loaded with the site instantly. In order to make it vary by election, it has to be stored within the election_json as an actual attribute.
- This will require going back and editing every mod preset to reflect this.
- The bigger issue, however, is editing the JS file. The JS file parses each JSON simultaneously with the rendering of the HTML.
- Attempting to edit the current line which renders the credits window to take the JSON as an input will make it unable to vary properly, since the variable *t* tracks the currently selected election.
- Variable *t* is accessed by the election summary window. Placing the credits line into the election summary window makes it unable to render outside of the box. 
- Creating a separate line there to render in the inner_window_2 div will allow you to access variable *t* fine, but it will also result in the whole thing being overwritten, since all elements in the div are expected to be rendered at once. 

This leaves two options IMO. Either we somehow create a new div which can store the credits window and set its position accordingly, or edit the JS file so that the line which renders inner_window_2 is able to reference the same information which is used to define variable *t*.

Will keep updated.

**Comment by Danxv33** [comment]
fixed a while ago
