### ISSUE TITLE
Event Codes

### ISSUE THREAD

**Issue by TomatDividedBy0** [newcampaigntrail/newcampaigntrail#45]
Allowing for a list of non-vanilla but standardized types of events that can be triggered by a question is something that I've theorycrafted and should be viable. 

Essentially, how it'd work is that the site's code has types of "events" pre-programmed, but how these events manifest can be customized in the Code 1/Code 2 blocks. Here's some examples of what kind of events would be possible:

- Switching VP midway, such as McGovern having to ditch Eagleton.
- Custom victory/loss-screen text depending on your actions. 

What would the procedure for implementing this look like?
1. Every "type" of event is assigned a custom code which remains standard across the site since it's site-side, let us say that a VP-switch is identified by code "EV001"
2. EV001 contains a set of arguments that it can take from the mod-creator. This here would be the VP-image, the VP-name, and possibly a candidate pk so you get its actual effects in-game (although I'm less confident about this last part working as easily). 
2. Inside the Code 2 block, under any single "Answer" object, there is an event_codes field in which you enter a list of key-value pairs, each item representing the event you'd like that answer to trigger. This may resemble `event_codes: ['EV001': [arg1, arg2...], 'EV002': [arg1, arg2...]`
3.  The key-half of each entry simply contains a text-string of the event code, so the game knows which function to reference.
4. The value-half is another list of key-value pairs which are formatted along the lines of `[running_mate_image_url: https://www.website.com/myimage.png, running_mate_last_name: Shriver]`. The arguments that can be taken would obviously vary depending on how the event is coded and we'd probably have to provide some sort of documentation.

**Comment by Danxv33** [comment]
Something like this will be added in the future (not to mention endings have already added the custom V/L screen stuff), so keep an eye out for that. Gonna close this for now.
