### ISSUE TITLE
Broken Candidate Pictures

### ISSUE THREAD

**Issue by biasface** [newcampaigntrail/newcampaigntrail#6]
2000 - Bush/Powell
![image](https://user-images.githubusercontent.com/43894316/115428339-4baf9600-a1d0-11eb-9fb2-2891cca0d7aa.png)
1968 - Humphrey/Muskie (he doesn't have a pic in the VP select either)
![image](https://user-images.githubusercontent.com/43894316/115427691-ae546200-a1cf-11eb-8468-58a17decb3de.png)
1948 - Truman/Barkley
![image](https://user-images.githubusercontent.com/43894316/115428125-130fbc80-a1d0-11eb-8525-c67deaaa1319.png)

**Comment by newcampaigntrail** [comment]
Fixed, though you can technically add Carson to the list.
