### ISSUE TITLE
Bug involving Mods

### ISSUE THREAD

**Issue by ZacharyTheGamer200** [newcampaigntrail/newcampaigntrail#60]
When the game is started the mod will first show information from the campaign the mod is based on (eg. the 2016 election in the case of the 2018 midterms).

**Comment by ItsAstronomical** [comment]
I'm not sure if you ever figured out the answer, but this isn't really an issue that's been focused on. It's a bit annoying, but players can go to the polling map to fix this issue. It's a very short term, visual bug. I'm no expert, but I have a feeling it's due to the way modding works.
