### ISSUE TITLE
All broken VPs

### ISSUE THREAD

**Issue by biasface** [newcampaigntrail/newcampaigntrail#7]
For these president/vp tickets, the game does not start.
2016a - Trump/Carson
2000 - Bush/Powell (The game does start, but doesn't let you past the first question.)
1968 - Humphrey/Connally 
1948 - Truman/Barkley (The game does start, but doesn't let you past the first question.)

**Comment by newcampaigntrail** [comment]
I just can't get Carson working. I am still trying, but all others should be good now.

**Comment by newcampaigntrail** [comment]
Carson seems to be working now.
